"""add_fk_indexes

Revision ID: 02c688e14b2b
Revises: 1778e8263c1c
Create Date: 2026-03-03 00:16:16.141233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c688e14b2b'
down_revision: Union[str, Sequence[str], None] = '1778e8263c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_incident_id'), ['incident_id'], unique=False)

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_scenario_id'), ['scenario_id'], unique=False)

    with op.batch_alter_table('interventiondata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventiondata_incident_id'), ['incident_id'], unique=True)

    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_exact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('victim_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('initial_emotion', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scenario_creator_id'), ['creator_id'], unique=False)
        batch_op.drop_column('initial_description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_description', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_scenario_creator_id'))
        batch_op.drop_column('initial_emotion')
        batch_op.drop_column('victim_status')
        batch_op.drop_column('location_exact')

    with op.batch_alter_table('interventiondata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventiondata_incident_id'))

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_incident_operator_id'))
        batch_op.drop_index(batch_op.f('ix_incident_creator_id'))

    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_incident_id'))

    # ### end Alembic commands ###
